# Generated by Django 2.2.7 on 2020-01-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='serial_number',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
